# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('regno', models.IntegerField()),
                ('date_of_issue', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('date_of_return', models.DateTimeField()),
                ('course', models.CharField(choices=[('BCA', 'BCA'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('B.Com', 'B.Com')], max_length=10)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
