# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libsys', '0003_auto_20160302_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('accno', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('publication', models.CharField(max_length=50)),
                ('edition', models.CharField(max_length=50)),
                ('no_of_copies', models.IntegerField()),
                ('volume', models.CharField(max_length=50)),
                ('date_purchase', models.DateField()),
                ('price', models.FloatField()),
                ('statud', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='accno',
            field=models.ForeignKey(default=12345, on_delete=django.db.models.deletion.CASCADE, to='libsys.Book'),
            preserve_default=False,
        ),
    ]
