# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libsys', '0004_auto_20160302_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='statud',
            new_name='status',
        ),
    ]
