# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libsys', '0005_auto_20160302_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine', models.FloatField()),
                ('accno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libsys.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField()),
                ('accno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libsys.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_return', models.DateField()),
                ('accno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libsys.Book')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_issue',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_return',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='return',
            name='regno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libsys.Student'),
        ),
        migrations.AddField(
            model_name='issue',
            name='regno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libsys.Student'),
        ),
        migrations.AddField(
            model_name='fine',
            name='regno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libsys.Student'),
        ),
    ]
